// try {
//      throw new Error('Algo salio mal');
// } catch (error) {
//      console.log(error);
// }

try {
     throw new Error('Algo salio mal');
} catch {
     console.log('Hubo un error bastante grave...');
}